### ISSUE TITLE
Problemas ao alterar campos de um model

### ISSUE THREAD

**Issue by Kal-0** [Kal-0/FDS#10]
Ao tentar dar alterar um campo de um dos nossos models e dar o migrate, percebi que as alteracoes nao tinham sido feitas, mesmo que o terminal nao apontasse para nenhum erro durante o processo. 
Apos pesquisar a respeito descobri que o Django nao possui uma funcao concreta para algo equivalente a um "ALTER_TABLE".
Entretanto descobri tambem que havia um jeito de contornar esse problema.

![image](https://user-images.githubusercontent.com/106926790/232142170-e6ce06c9-2c79-4b21-9a93-677ba2627809.png)
.

Consegui "solucionar" esse problema apagando os aquivos de registro dentro da pasta "migrations". Aparentemente eles causavam alguma incoerencia na hora de fazer as migrations.
![image](https://user-images.githubusercontent.com/106926790/232143910-0ab5be51-7c3c-4aee-82a9-4a265fad65da.png)
.

Apos apagar esses arquivos basta fazer os migrations normalmente que as alteracoes serao salvas.
![image](https://user-images.githubusercontent.com/106926790/232144273-5a067c09-3081-4dc8-8e3f-08f111feabe0.png)
.

Mesmo funcionando dessa maneira nao acho que seja uma boa pratica, precisamos pesquisar mais a respeito!

**Comment by DiogoHMC** [comment]
Pode ser que ele esteja "pegando" algumas coisas do migrate anteriror sabe. Mas tbm acho q poderiamos ver esse problema, ou ate perguntar a algum monitor
