### ISSUE TITLE
Criar publicação não esta salvando a imagem como URL e sim em arquivo de imagem

### ISSUE THREAD

**Issue by DiogoHMC** [Kal-0/FDS#21]
![image](https://github.com/Kal-0/FDS/assets/116087739/f9058bf2-13d3-41b1-ae0b-b9784b931e47)

CRIADO APARTIR DO ADICIONAR ANUNCIO

![image](https://github.com/Kal-0/FDS/assets/116087739/691a01a5-9596-4005-b649-95e0a7805535)

CRIADO APARTIR DO ADM

**Comment by DiogoHMC** [comment]
Problema ocorre quando vamos adicionar um anuncio e a img dele esta indo como formato de img bruto. Eu acho q a soloção é na hora de pegar o dado da imagem transformar ela em .url para ir pro DB.

**Comment by Kal-0** [comment]
O problema se encontrava no tipo de forms dentro do arquivo html da página. Seu tipo foi alterado para multipart, assim permitindo que arquivos fossem enviados pelo método POST.
