### ISSUE TITLE
Apresenta a categoria mesmo sem nenhum item atribuido a ele.

### ISSUE THREAD

**Issue by DiogoHMC** [Kal-0/FDS#31]
![image](https://github.com/Kal-0/FDS/assets/116087739/69045edf-e8ad-4d5d-a3a7-1eaf7b181489)

Isso acontece quando o usuario exclui o ultimo anuncio relacionado a sua categoria

**Comment by SofiaValadares** [comment]
problema concertado no commit 523, adicionado um filtro que verifica se existem itens na categoria antes de imprimi-la no html
