### ISSUE TITLE
Cadastro

### ISSUE THREAD

**Issue by DiogoHMC** [Kal-0/FDS#8]
![image](https://user-images.githubusercontent.com/116087739/232131828-f2e400a2-9b23-45b6-a3a2-f632b2213936.png)

**Comment by DiogoHMC** [comment]
preciso de ajuda na parte de cadastro, o html estava falantando uma senha de confirmação e faltando o form. Vejam se conseguem tirar algo dai

**Comment by Kal-0** [comment]
ta falando ai q tu ta chamando uma classe model chamada de "ModelForm", mas ela nao existe.
vc criou e chamou esse model ou e padrao do proprio django?

**Comment by DiogoHMC** [comment]
Eu acho q ja esta criado, pq n tem nenhuma variavel com esse nome. Será q eu preciso da o import no html?
N sei se tu deu algum pull hj mas eu atualizei algumas partes.

**Comment by Kal-0** [comment]
Eu acho q o problema envolve essas 2 partes do codigo:
![image](https://user-images.githubusercontent.com/106926790/232148833-8dacc4ad-37f7-4f0e-836d-aac1a8e74d6c.png)
.
![image](https://user-images.githubusercontent.com/106926790/232148866-b687f4d8-f6d8-414b-bd66-961f762479eb.png)
.
E possivelmente todas as partes do "cadastro.html" que coletem dados do usuario.

**Comment by DiogoHMC** [comment]
Pensando agr acho q é isso msm, tu desse uma olhada no HTML?
Vou refazer achei um video legal e possivelmente me ajuda nisso
